services:
  database:
    image: mysql:8.4.6
    restart: always
    ports:
      #Host Port : Container Port
      #Spring sends data to the host port, which is configured to be 3307.
      #But docker tells Linux to forward traffic from 3307 to port 3306
      #where the docker container is listening
      #The significance, is that this lets me direct the data stream
      #between ports/containers. Especially important when I have multiple
      #containers.
      - "${DB_PORTS}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      #Docker interprets the below as mysqladmin ping-h localhost
      #CMD is docker syntax.
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      #Run this check every 5s
      interval: 5s
      #If the check takes > 3s, the attempt failed
      timeout: 3s
      #If 5 consecutive failures occur, the container is unhealthy
      retries: 5
      #Give Mysql 10s to start up before failures count
      start_period: 10s


#W/o volume, if I bring the container down - the data is wiped. Because
#volumes configures docker to setup DB files so they persist after the
#container is brought down.
volumes:
  mysql_data:

#After bringing down the container, run: sudo docker volume ls.
#This confirms that the db files are still